# Generated by Django 2.2.5 on 2022-08-23 05:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('parent_commit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('merged_commit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
                ('project_original_id', models.CharField(blank=True, max_length=255, null=True)),
                ('series_original_id', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('msg_id', models.CharField(max_length=255)),
                ('msg_content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_to_msg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('change_id', models.IntegerField(blank=True, null=True)),
                ('mailing_list_id', models.IntegerField(blank=True, null=True)),
                ('submitter_original_id', models.CharField(blank=True, max_length=255, null=True)),
                ('patch_original_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_original_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sender_email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('project_original_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_content', models.TextField(blank=True, null=True)),
                ('code_diff', models.TextField(blank=True, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('change_id', models.IntegerField(blank=True, null=True)),
                ('mailing_list_id', models.IntegerField(blank=True, null=True)),
                ('series_original_id', models.CharField(blank=True, max_length=255, null=True)),
                ('submitter_original_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_original_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('repo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('list_id', models.CharField(blank=True, max_length=255, null=True)),
                ('list_address', models.CharField(blank=True, max_length=255, null=True)),
                ('maintainers', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('received_total', models.IntegerField(blank=True, null=True)),
                ('cover_letter_content', models.TextField(blank=True, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('project_original_id', models.CharField(blank=True, max_length=255, null=True)),
                ('submitter_original_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
