# Generated by Django 2.2.5 on 2022-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='msg_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_msg_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patch',
            name='msg_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
