# Generated by Django 3.2.15 on 2023-11-21 12:54

from django.db import migrations, models
import django.db.models.deletion
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExactBoWGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('parent_commit_id', models.TextField(blank=True, null=True)),
                ('merged_commit_id', models.TextField(blank=True, null=True)),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
                ('inspection_needed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_maintainer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('msg_id', models.TextField(blank=True, null=True, unique=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('content', models.FileField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='https://127.0.0.1:8000/textfiles/', collection='textfiles'), upload_to='mailing_list_email_content')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('cover_letter_msg_id', models.TextField(blank=True, null=True)),
                ('inspection_needed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OWDiffGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('parent_commit_id', models.TextField(blank=True, null=True)),
                ('merged_commit_id', models.TextField(blank=True, null=True)),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
                ('inspection_needed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('repository_url', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('list_id', models.CharField(blank=True, max_length=255, null=True)),
                ('list_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('received_total', models.IntegerField(blank=True, null=True)),
                ('cover_letter_msg_id', models.TextField(blank=True, null=True)),
                ('cover_letter_content', models.FileField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='https://127.0.0.1:8000/textfiles/', collection='textfiles'), upload_to='series_cover_letter_content')),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.CASCADE, to='patchwork.project', to_field='original_id')),
                ('submitter_identity', models.ForeignKey(blank=True, db_column='submitter_identity', null=True, on_delete=django.db.models.deletion.RESTRICT, to='patchwork.identity', to_field='original_id')),
                ('submitter_individual', models.ForeignKey(blank=True, db_column='submitter_individual', null=True, on_delete=django.db.models.deletion.RESTRICT, to='patchwork.individual', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIdentityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_original_id', models.ForeignKey(db_column='identity_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.identity', to_field='original_id')),
                ('project_original_id', models.ForeignKey(db_column='project_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.project', to_field='original_id')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='maintainer_identity',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.ProjectIdentityRelation', to='patchwork.Identity'),
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('msg_id', models.TextField(blank=True, null=True)),
                ('msg_content', models.FileField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='https://127.0.0.1:8000/textfiles/', collection='textfiles'), upload_to='patch_msg_content')),
                ('code_diff', models.FileField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='https://127.0.0.1:8000/textfiles/', collection='textfiles'), upload_to='patch_code_diff')),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_ref', models.TextField(blank=True, null=True)),
                ('in_reply_to', models.TextField(blank=True, null=True)),
                ('change1', models.ForeignKey(blank=True, db_column='change1', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='patches', to='patchwork.exactbowgroup', to_field='original_id')),
                ('change2', models.ForeignKey(blank=True, db_column='change2', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='patches', to='patchwork.owdiffgroup', to_field='original_id')),
                ('mailinglist', models.ForeignKey(blank=True, db_column='mailinglist', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='patches', to='patchwork.mailinglist', to_field='original_id')),
                ('newseries', models.ForeignKey(blank=True, db_column='newseries', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='patches', to='patchwork.newseries', to_field='original_id')),
                ('project', models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.RESTRICT, to='patchwork.project', to_field='original_id')),
                ('series', models.ForeignKey(blank=True, db_column='series', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='patches', to='patchwork.series', to_field='original_id')),
                ('submitter_identity', models.ForeignKey(blank=True, db_column='submitter_identity', null=True, on_delete=django.db.models.deletion.RESTRICT, to='patchwork.identity', to_field='original_id')),
                ('submitter_individual', models.ForeignKey(blank=True, db_column='submitter_individual', null=True, on_delete=django.db.models.deletion.RESTRICT, to='patchwork.individual', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='OWDiffGroupSeriesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change2_original_id', models.ForeignKey(db_column='change2_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.owdiffgroup', to_field='original_id')),
                ('series_original_id', models.ForeignKey(db_column='series_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.series', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='OWDiffGroupNewSeriesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change2_original_id', models.ForeignKey(db_column='change2_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.owdiffgroup', to_field='original_id')),
                ('newseries_original_id', models.ForeignKey(db_column='newseries_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.newseries', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='OWDiffGroupIndividualRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change2_original_id', models.ForeignKey(db_column='change2_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.owdiffgroup', to_field='original_id')),
                ('individual_original_id', models.ForeignKey(db_column='individual_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.individual', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='OWDiffGroupIdentityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change2_original_id', models.ForeignKey(db_column='change2_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.owdiffgroup', to_field='original_id')),
                ('identity_original_id', models.ForeignKey(db_column='identity_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.identity', to_field='original_id')),
            ],
        ),
        migrations.AddField(
            model_name='owdiffgroup',
            name='newseries',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.OWDiffGroupNewSeriesRelation', to='patchwork.NewSeries'),
        ),
        migrations.AddField(
            model_name='owdiffgroup',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.CASCADE, to='patchwork.project', to_field='original_id'),
        ),
        migrations.AddField(
            model_name='owdiffgroup',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.OWDiffGroupSeriesRelation', to='patchwork.Series'),
        ),
        migrations.AddField(
            model_name='owdiffgroup',
            name='submitter_identity',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.OWDiffGroupIdentityRelation', to='patchwork.Identity'),
        ),
        migrations.AddField(
            model_name='owdiffgroup',
            name='submitter_individual',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.OWDiffGroupIndividualRelation', to='patchwork.Individual'),
        ),
        migrations.CreateModel(
            name='NewSeriesSeriesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newseries_original_id', models.ForeignKey(db_column='newseries_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.newseries', to_field='original_id')),
                ('series_original_id', models.ForeignKey(db_column='series_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.series', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='NewSeriesIndividualRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_original_id', models.ForeignKey(db_column='individual_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.individual', to_field='original_id')),
                ('newseries_original_id', models.ForeignKey(db_column='newseries_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.newseries', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='NewSeriesIdentityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_original_id', models.ForeignKey(db_column='identity_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.identity', to_field='original_id')),
                ('newseries_original_id', models.ForeignKey(db_column='newseries_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.newseries', to_field='original_id')),
            ],
        ),
        migrations.AddField(
            model_name='newseries',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.CASCADE, to='patchwork.project', to_field='original_id'),
        ),
        migrations.AddField(
            model_name='newseries',
            name='series',
            field=models.ManyToManyField(blank=True, through='patchwork.NewSeriesSeriesRelation', to='patchwork.Series'),
        ),
        migrations.AddField(
            model_name='newseries',
            name='submitter_identity',
            field=models.ManyToManyField(blank=True, through='patchwork.NewSeriesIdentityRelation', to='patchwork.Identity'),
        ),
        migrations.AddField(
            model_name='newseries',
            name='submitter_individual',
            field=models.ManyToManyField(blank=True, through='patchwork.NewSeriesIndividualRelation', to='patchwork.Individual'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.CASCADE, to='patchwork.project', to_field='original_id'),
        ),
        migrations.CreateModel(
            name='IndividualIdentityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_original_id', models.ForeignKey(db_column='identity_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.identity', to_field='original_id')),
                ('individual_original_id', models.ForeignKey(db_column='individual_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.individual', to_field='original_id')),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='identity',
            field=models.ManyToManyField(blank=True, null=True, related_name='individuals', through='patchwork.IndividualIdentityRelation', to='patchwork.Identity'),
        ),
        migrations.AddField(
            model_name='individual',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.CASCADE, to='patchwork.project', to_field='original_id'),
        ),
        migrations.CreateModel(
            name='ExactBoWGroupSeriesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change1_original_id', models.ForeignKey(db_column='change1_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.exactbowgroup', to_field='original_id')),
                ('series_original_id', models.ForeignKey(db_column='series_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.series', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='ExactBoWGroupNewSeriesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change1_original_id', models.ForeignKey(db_column='change1_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.exactbowgroup', to_field='original_id')),
                ('newseries_original_id', models.ForeignKey(db_column='newseries_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.newseries', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='ExactBoWGroupIndividualRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change1_original_id', models.ForeignKey(db_column='change1_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.exactbowgroup', to_field='original_id')),
                ('individual_original_id', models.ForeignKey(db_column='individual_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.individual', to_field='original_id')),
            ],
        ),
        migrations.CreateModel(
            name='ExactBoWGroupIdentityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change1_original_id', models.ForeignKey(db_column='change1_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.exactbowgroup', to_field='original_id')),
                ('identity_original_id', models.ForeignKey(db_column='identity_original_id', on_delete=django.db.models.deletion.CASCADE, to='patchwork.identity', to_field='original_id')),
            ],
        ),
        migrations.AddField(
            model_name='exactbowgroup',
            name='newseries',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.ExactBoWGroupNewSeriesRelation', to='patchwork.NewSeries'),
        ),
        migrations.AddField(
            model_name='exactbowgroup',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.CASCADE, to='patchwork.project', to_field='original_id'),
        ),
        migrations.AddField(
            model_name='exactbowgroup',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.ExactBoWGroupSeriesRelation', to='patchwork.Series'),
        ),
        migrations.AddField(
            model_name='exactbowgroup',
            name='submitter_identity',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.ExactBoWGroupIdentityRelation', to='patchwork.Identity'),
        ),
        migrations.AddField(
            model_name='exactbowgroup',
            name='submitter_individual',
            field=models.ManyToManyField(blank=True, null=True, through='patchwork.ExactBoWGroupIndividualRelation', to='patchwork.Individual'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255, unique=True)),
                ('msg_id', models.TextField(blank=True, null=True)),
                ('msg_content', models.FileField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='https://127.0.0.1:8000/textfiles/', collection='textfiles'), upload_to='comment_msg_content')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('in_reply_to', models.TextField(blank=True, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('change1', models.ForeignKey(blank=True, db_column='change1', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='patchwork.exactbowgroup', to_field='original_id')),
                ('change2', models.ForeignKey(blank=True, db_column='change2', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='patchwork.owdiffgroup', to_field='original_id')),
                ('mailinglist', models.ForeignKey(blank=True, db_column='mailinglist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='patchwork.mailinglist', to_field='original_id')),
                ('patch', models.ForeignKey(blank=True, db_column='patch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='patchwork.patch', to_field='original_id')),
                ('project', models.ForeignKey(blank=True, db_column='project', null=True, on_delete=django.db.models.deletion.RESTRICT, to='patchwork.project', to_field='original_id')),
                ('submitter_identity', models.ForeignKey(blank=True, db_column='submitter_identity', null=True, on_delete=django.db.models.deletion.RESTRICT, to='patchwork.identity', to_field='original_id')),
                ('submitter_individual', models.ForeignKey(blank=True, db_column='submitter_individual', null=True, on_delete=django.db.models.deletion.RESTRICT, to='patchwork.individual', to_field='original_id')),
            ],
        ),
    ]
